### ISSUE TITLE
Discord messages not forwarding to Minecraft server after a certain period

### ISSUE THREAD

**Issue by Axrce** [carlop3333/DiscordBDS#5]
Ive come across a problem with the DiscordBDS. After a while, Discord messages aren't getting through to the Minecraft server anymore. Strangely, messages from the Minecraft server are still being sent and displayed correctly on Discord.

![image](https://github.com/carlop3333/DiscordBDS/assets/96381335/eec3dbb5-479f-42ab-9830-34158a69140f)

**Comment by carlop3333** [comment]
No ETA of this until rewrite...
